
version: '3.1'

services:
  event-db:
    image: postgres
    container_name: event-db
    environment:
      POSTGRES_USER: event-service
      POSTGRES_PASSWORD: event-service-pass
    ports:
      - "5433:5432"

  user-db:
    image: postgres
    container_name: user-db
    environment:
      POSTGRES_USER: user-service
      POSTGRES_PASSWORD: user-service-pass
    ports:
      - "5432:5432"

  ticket-db:
    image: postgres
    container_name: ticket-db
    environment:
      POSTGRES_USER: ticket-service
      POSTGRES_PASSWORD: ticket-service-pass
    ports:
      - "5434:5432"
