service:
  auth:
    username: 'automation'
    password: 'password'

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: false
  datasource:
    url: jdbc:postgresql://localhost:5434/ticket-service
    username: ticket-service
    password: ticket-service-pass

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

server:
  port: 8081
